#!/bin/bash

set -euo pipefail

BASE_DIR=/zhdd/home/tjshen/260415_ArcherA100
RUN_TS=${RUN_TS:-$(date +%Y%m%d_%H%M%S)}
GPU_TAG=${CUDA_VISIBLE_DEVICES:-auto}
GPU_TAG=${GPU_TAG//,/}
GPU_TAG=${GPU_TAG// /}

export CONDA_ENV_NAME=${CONDA_ENV_NAME:-llama2_vllm_copy}
export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
export MODEL_PATH=${MODEL_PATH:-/zhdd/models/Qwen2.5-1.5B-Instruct}
export REWARD_MODEL_PATH=${REWARD_MODEL_PATH:-/zhdd/home/tjshen/260413_Backup_model_resume_20260323_031320/Skywork-Reward-Llama-3.1-8B-v0.2}

export PROJECT_NAME=${PROJECT_NAME:-ArcherCodeR-V13-Qwen25-1_5B-5A100}
export EXP_NAME=${EXP_NAME:-train_5a100_v13_qwen25_1_5b_1gpu_gpu${GPU_TAG}_bsz${TRAIN_PROMPT_BSZ:-32}_save100_${RUN_TS}}
export OUTPUT_ROOT=${OUTPUT_ROOT:-./output_5A100_single}
export DYNAMIC_METHOD=${DYNAMIC_METHOD:-sample_taylor_v13}
export TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-2000}
export SAVE_FREQ=${SAVE_FREQ:-100}

export TRAIN_PROMPT_BSZ=${TRAIN_PROMPT_BSZ:-32}
export TRAIN_PROMPT_MINI_BSZ=${TRAIN_PROMPT_MINI_BSZ:-16}
export ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.70}

export SHADOW_ANCHOR_SIZE_PER_DOMAIN=${SHADOW_ANCHOR_SIZE_PER_DOMAIN:-128}
export GRAD_PROJECTION_DIM=${GRAD_PROJECTION_DIM:-256}
export CURVATURE_REFRESH_FREQ=${CURVATURE_REFRESH_FREQ:-50}

export RUNTIME_DIR=${RUNTIME_DIR:-"${BASE_DIR}/tq1_${RUN_TS}"}
# Keep Ray's temp path short enough for AF_UNIX socket limits.
export RAY_TMPDIR=${RAY_TMPDIR:-"${BASE_DIR}/rq"}
export RAY_PORT=${RAY_PORT:-6581}
export RAY_RUNTIME_ENV_AGENT_PORT=${RAY_RUNTIME_ENV_AGENT_PORT:-35801}
export RAY_DASHBOARD_AGENT_LISTEN_PORT=${RAY_DASHBOARD_AGENT_LISTEN_PORT:-35802}
export RAY_DASHBOARD_AGENT_GRPC_PORT=${RAY_DASHBOARD_AGENT_GRPC_PORT:-35803}
export RAY_METRICS_EXPORT_PORT=${RAY_METRICS_EXPORT_PORT:-35805}
export RAY_OBJECT_MANAGER_PORT=${RAY_OBJECT_MANAGER_PORT:-35806}
export RAY_NODE_MANAGER_PORT=${RAY_NODE_MANAGER_PORT:-35807}
export RAY_MIN_WORKER_PORT=${RAY_MIN_WORKER_PORT:-35810}
export RAY_MAX_WORKER_PORT=${RAY_MAX_WORKER_PORT:-35999}

export RAY_NUM_CPUS=${RAY_NUM_CPUS:-24}
export RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES=${RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES:-1}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec "${SCRIPT_DIR}/dynamic_train_v13_a100_formal.sh"
