#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export PROJECT_NAME=${PROJECT_NAME:-ArcherCodeR-V13-A100}
export EXP_NAME=${EXP_NAME:-train_v13_a100_sample_taylor_save100}
export OUTPUT_ROOT=${OUTPUT_ROOT:-./output_5090_Lian_v15}
export DYNAMIC_METHOD=${DYNAMIC_METHOD:-sample_taylor_v13}
export TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-1000}
export SAVE_FREQ=${SAVE_FREQ:-100}
export SAVE_STEPS=${SAVE_STEPS:-10}
export TRAIN_PROMPT_BSZ=${TRAIN_PROMPT_BSZ:-32}
export TRAIN_PROMPT_MINI_BSZ=${TRAIN_PROMPT_MINI_BSZ:-8}
export ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.65}
export SHADOW_ANCHOR_SIZE_PER_DOMAIN=${SHADOW_ANCHOR_SIZE_PER_DOMAIN:-128}
export GRAD_PROJECTION_DIM=${GRAD_PROJECTION_DIM:-256}
export CURVATURE_REFRESH_FREQ=${CURVATURE_REFRESH_FREQ:-50}

exec "${SCRIPT_DIR}/dynamic_train_v13_a100_smoke_bsz4_20step.sh"
