#!/bin/bash
set -euo pipefail

BASE_DIR=/zhdd/home/tjshen/260415_ArcherA100
RUN_TS=${RUN_TS:-$(date +%Y%m%d_%H%M%S)}

export CONDA_ENV_NAME=${CONDA_ENV_NAME:-llama2_vllm_copy}
export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,7}
export MODEL_PATH=${MODEL_PATH:-/zhdd/home/tjshen/models/Qwen2.5-1.5B-Instruct}
export REWARD_MODEL_PATH=${REWARD_MODEL_PATH:-/zhdd/home/tjshen/260413_Backup_model_resume_20260323_031320/Skywork-Reward-Llama-3.1-8B-v0.2}

export PROJECT_NAME=${PROJECT_NAME:-ArcherCodeR-V13grad-Qwen25-1_5B-8A100}
export EXP_NAME=${EXP_NAME:-train_8a100_v13grad_qwen25_1_5b_2gpu_07_bsz96_${RUN_TS}}
export OUTPUT_ROOT=${OUTPUT_ROOT:-${BASE_DIR}/v13_grad/output_8A100}
export DYNAMIC_METHOD=${DYNAMIC_METHOD:-sample_taylor_v13}
export TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-2000}
export SAVE_FREQ=${SAVE_FREQ:-100}
export SAVE_STEPS=${SAVE_STEPS:-10}

export TRAIN_PROMPT_BSZ=${TRAIN_PROMPT_BSZ:-96}
export TRAIN_PROMPT_MINI_BSZ=${TRAIN_PROMPT_MINI_BSZ:-48}
export ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.70}

export SHADOW_ANCHOR_SIZE_PER_DOMAIN=${SHADOW_ANCHOR_SIZE_PER_DOMAIN:-128}
export CANDIDATE_MULTIPLIER=${CANDIDATE_MULTIPLIER:-4}
export GRAD_PROJECTION_DIM=${GRAD_PROJECTION_DIM:-256}
export CURVATURE_REFRESH_FREQ=${CURVATURE_REFRESH_FREQ:-50}
export FULL_DATASET_EMBEDDING_BATCH_SIZE=${FULL_DATASET_EMBEDDING_BATCH_SIZE:-4}
export FULL_TRAIN_MAX_SAMPLES_PER_CATEGORY=${FULL_TRAIN_MAX_SAMPLES_PER_CATEGORY:-4}
export FULL_TARGET_MAX_SAMPLES_PER_CATEGORY=${FULL_TARGET_MAX_SAMPLES_PER_CATEGORY:-4}

export TRAIN_FILE=${TRAIN_FILE:-${BASE_DIR}/v13/data/train/Mix_AirRep_nonrepeated_sysprom.json}
export TEST_FILE=${TEST_FILE:-${BASE_DIR}/v13/data/test/livecodebench_v5.json}
export TARGET_MATH_FILE=${TARGET_MATH_FILE:-${BASE_DIR}/v13/data/test/AIME2025.json}
export TARGET_CODE_FILE=${TARGET_CODE_FILE:-${BASE_DIR}/v13/data/test/LCB.json}
export TARGET_GENERAL_FILE=${TARGET_GENERAL_FILE:-${BASE_DIR}/v13/data/test/Arena_question.json}

export DISABLE_PYTORCH_CUDA_ALLOC_CONF=1

export RUNTIME_DIR=${RUNTIME_DIR:-${BASE_DIR}/t_v13grad_${RUN_TS}}
export RAY_TMPDIR=${RAY_TMPDIR:-${BASE_DIR}/rv13g}
export RAY_PORT=${RAY_PORT:-6788}
export RAY_RUNTIME_ENV_AGENT_PORT=${RAY_RUNTIME_ENV_AGENT_PORT:-30201}
export RAY_DASHBOARD_AGENT_LISTEN_PORT=${RAY_DASHBOARD_AGENT_LISTEN_PORT:-30202}
export RAY_DASHBOARD_AGENT_GRPC_PORT=${RAY_DASHBOARD_AGENT_GRPC_PORT:-30203}
export RAY_METRICS_EXPORT_PORT=${RAY_METRICS_EXPORT_PORT:-30205}
export RAY_OBJECT_MANAGER_PORT=${RAY_OBJECT_MANAGER_PORT:-30206}
export RAY_NODE_MANAGER_PORT=${RAY_NODE_MANAGER_PORT:-30207}
export RAY_MIN_WORKER_PORT=${RAY_MIN_WORKER_PORT:-31200}
export RAY_MAX_WORKER_PORT=${RAY_MAX_WORKER_PORT:-39999}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec "${SCRIPT_DIR}/dynamic_train_v13_a100_formal.sh"
